# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a7e7ca0a3d5672512569af68f7f1d1ff2224820bdd65bd97e650f2edcfd2885a80c0b190a4f5e604a7b41186a37aae82c23125bd23a0e7e7e3f9a1abd7b5965

test:
  secret_key_base: fd1aa4c3d7be60d394c485552c85bab5443675635a9b9844548601ad1a479e33f890a174c6b763e940fc1e1a8040e5688d9af01aff63fba2b505fc69b0c6192b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
